In [5]:
pip install pandas_gbq
pip install google-cloud-bigquery

SyntaxError: invalid syntax (3546952622.py, line 1)

In [1]:
## Objetivo: importar un dataset, entender qu√© datos hay, crear una nueva columna, analizarla y guardarlo.

import pandas as pd

In [2]:
# Importar datos de COVID de la web con Pandas (https://covidtracking.com/data/api)
df = pd.read_csv('https://api.covidtracking.com/v1/states/daily.csv')
df

,date,state,positive,probableCases,negative,pending,totalTestResultsSource,totalTestResults,hospitalizedCurrently,hospitalizedCumulative,...,dataQualityGrade,deathIncrease,hospitalizedIncrease,hash,commercialScore,negativeRegularScore,negativeScore,positiveScore,score,grade
0,20210307,AK,56886.0,NaN,NaN,NaN,totalTestsViral,1731628.0,33.0,1293.0,...,NaN,0,0,dc4bccd4bb885349d7e94d6fed058e285d4be164,0,0,0,0,0,NaN
1,20210307,AL,499819.0,107742.0,1931711.0,NaN,totalTestsPeopleViral,2323788.0,494.0,45976.0,...,NaN,-1,0,997207b430824ea40b8eb8506c19a93e07bc972e,0,0,0,0,0,NaN
2,20210307,AR,324818.0,69092.0,2480716.0,NaN,totalTestsViral,2736442.0,335.0,14926.0,...,NaN,22,11,50921aeefba3e30d31623aa495b47fb2ecc72fae,0,0,0,0,0,NaN
3,20210307,AS,0.0,NaN,2140.0,NaN,totalTestsViral,2140.0,NaN,NaN,...,NaN,0,0,f77912d0b80d579fbb6202fa1a90554fc4dc1443,0,0,0,0,0,NaN
4,20210307,AZ,826454.0,56519.0,3073010.0,NaN,totalTestsViral,7908105.0,963.0,57907.0,...,NaN,5,44,0437a7a96f4471666f775e63e86923eb5cbd8cdf,0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20775,20200117,WA,0.0,NaN,NaN,NaN,totalTestEncountersViral,NaN,NaN,NaN,...,NaN,0,0,7cefac6b3681020741ca30f45399a7b22f2e45b4,0,0,0,0,0,NaN
20776,20200116,WA,0.0,NaN,NaN,NaN,totalTestEncountersViral,NaN,NaN,NaN,...,NaN,0,0,650501e005a5ee86d93c5f32dda56735ea2af967,0,0,0,0,0,NaN
20777,20200115,WA,0.0,NaN,NaN,NaN,totalTestEncountersViral,NaN,NaN,NaN,...,NaN,0,0,4987e61aad88182abfe641033b597304c2153d4f,0,0,0,0,0,NaN
20778,20200114,WA,0.0,NaN,NaN,NaN,totalTestEncountersViral,NaN,NaN,NaN,...,NaN,0,0,1881c8a2f0d337b22066b4f05df06eb2259e8d57,0,0,0,0,0,NaN
20779,20200113,WA,NaN,NaN,NaN,NaN,totalTestEncountersViral,NaN,NaN,NaN,...,NaN,0,0,12b994ad07c276a5278a2465e081751688739765,0,0,0,0,0,NaN

In [3]:
# Vemos que info hay
df.head()
df.columns
df.shape
df.info()
df.describe() # resumen de las variables numericas

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20780 entries, 0 to 20779
Data columns (total 56 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   date                         20780 non-null  int64
 1   state                        20780 non-null  object
 2   positive                     20592 non-null  float64
 3   probableCases                9271 non-null   float64
 4   negative                     13290 non-null  float64
 5   pending                      2138 non-null   float64
 6   totalTestResultsSource       20780 non-null  object
 7   totalTestResults             20614 non-null  float64
 8   hospitalizedCurrently        17339 non-null  float64
 9   hospitalizedCumulative       12382 non-null  float64
 10  inIcuCurrently               11636 non-null  float64
 11  inIcuCumulative              3789 non-null   float64
 12  onVentilatorCurrently        9126 non-null   float64
 13  onVentilatorCumulative       1290 non-null   float64
 14  recovered                    12003 non-null  float64
 15  lastUpdateEt                 20164 non-null  object
 16  dateModified                 20164 non-null  object
 17  checkTimeEt                  20164 non-null  object
 18  death                        19930 non-null  float64
 19  hospitalized                 12382 non-null  float64
 20  hospitalizedDischarged       3070 non-null   float64
 21  dateChecked                  20164 non-null  object
 22  totalTestsViral              14516 non-null  float64
 23  positiveTestsViral           8958 non-null   float64
 24  negativeTestsViral           5024 non-null   float64
 25  positiveCasesViral           14246 non-null  float64
 26  deathConfirmed               9422 non-null   float64
 27  deathProbable                7593 non-null   float64
 28  totalTestEncountersViral     5231 non-null   float64
 29  totalTestsPeopleViral        9197 non-null   float64
 30  totalTestsAntibody           4789 non-null   float64
 31  positiveTestsAntibody        3346 non-null   float64
 32  negativeTestsAntibody        1458 non-null   float64
 33  totalTestsPeopleAntibody     2200 non-null   float64
 34  positiveTestsPeopleAntibody  1094 non-null   float64
 35  negativeTestsPeopleAntibody  972 non-null    float64
 36  totalTestsPeopleAntigen      999 non-null    float64
 37  positiveTestsPeopleAntigen   633 non-null    float64
 38  totalTestsAntigen            3421 non-null   float64
 39  positiveTestsAntigen         2233 non-null   float64
 40  fips                         20780 non-null  int64
 41  positiveIncrease             20780 non-null  int64
 42  negativeIncrease             20780 non-null  int64
 43  total                        20780 non-null  int64
 44  totalTestResultsIncrease     20780 non-null  int64
 45  posNeg                       20780 non-null  int64
 46  dataQualityGrade             0 non-null      float64
 47  deathIncrease                20780 non-null  int64
 48  hospitalizedIncrease         20780 non-null  int64
 49  hash                         20780 non-null  object
 50  commercialScore              20780 non-null  int64
 51  negativeRegularScore         20780 non-null  int64
 52  negativeScore                20780 non-null  int64
 53  positiveScore                20780 non-null  int64
 54  score                        20780 non-null  int64
 55  grade                        0 non-null      float64
dtypes: float64(35), int64(14), object(7)
memory usage: 8.9+ MB

,date,positive,probableCases,negative,pending,totalTestResults,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,...,posNeg,dataQualityGrade,deathIncrease,hospitalizedIncrease,commercialScore,negativeRegularScore,negativeScore,positiveScore,score,grade
count,2.078000e+04,2.059200e+04,9271.000000,1.329000e+04,2138.000000,2.061400e+04,17339.000000,12382.000000,11636.000000,3789.000000,...,2.078000e+04,0.0,20780.000000,20780.000000,20780.0,20780.0,20780.0,20780.0,20780.0,0.0
mean,2.020244e+07,1.651560e+05,21729.123719,8.482246e+05,1659.862956,2.186936e+06,1190.576965,9262.762478,359.621176,1934.191607,...,7.061500e+05,NaN,24.790712,37.360780,0.0,0.0,0.0,0.0,0.0,NaN
std,3.608732e+03,3.267852e+05,45471.459778,1.344501e+06,4671.028548,4.436508e+06,2060.041207,12620.544081,594.831150,1953.329983,...,1.299997e+06,NaN,60.162742,208.237151,0.0,0.0,0.0,0.0,0.0,NaN
min,2.020011e+07,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,1.000000,0.000000,6.000000,...,0.000000e+00,NaN,-201.000000,-12257.000000,0.0,0.0,0.0,0.0,0.0,NaN
25%,2.020060e+07,5.753750e+03,773.500000,5.394125e+04,43.000000,1.040498e+05,166.500000,985.250000,60.000000,501.000000,...,2.565875e+04,NaN,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,NaN
50%,2.020090e+07,4.606450e+04,4491.000000,3.059720e+05,212.500000,6.552670e+05,531.000000,4472.000000,172.000000,1295.000000,...,1.935810e+05,NaN,6.000000,0.000000,0.0,0.0,0.0,0.0,0.0,NaN
75%,2.020120e+07,1.779580e+05,19553.000000,1.056611e+06,1295.750000,2.264766e+06,1279.000000,12248.500000,380.000000,2451.000000,...,7.737408e+05,NaN,24.000000,36.000000,0.0,0.0,0.0,0.0,0.0,NaN
max,2.021031e+07,3.501394e+06,365961.000000,1.018694e+07,64400.000000,4.964601e+07,22851.000000,82237.000000,5225.000000,9263.000000,...,1.124825e+07,NaN,2559.000000,16373.000000,0.0,0.0,0.0,0.0,0.0,NaN

In [4]:
# Ordenar datos
df
df.sort_values(by='date', ascending=True) # inplace = True si queremos que esto afecte al DF

,date,state,positive,probableCases,negative,pending,totalTestResultsSource,totalTestResults,hospitalizedCurrently,hospitalizedCumulative,...,dataQualityGrade,deathIncrease,hospitalizedIncrease,hash,commercialScore,negativeRegularScore,negativeScore,positiveScore,score,grade
20779,20200113,WA,NaN,NaN,NaN,NaN,totalTestEncountersViral,NaN,NaN,NaN,...,NaN,0,0,12b994ad07c276a5278a2465e081751688739765,0,0,0,0,0,NaN
20778,20200114,WA,0.0,NaN,NaN,NaN,totalTestEncountersViral,NaN,NaN,NaN,...,NaN,0,0,1881c8a2f0d337b22066b4f05df06eb2259e8d57,0,0,0,0,0,NaN
20777,20200115,WA,0.0,NaN,NaN,NaN,totalTestEncountersViral,NaN,NaN,NaN,...,NaN,0,0,4987e61aad88182abfe641033b597304c2153d4f,0,0,0,0,0,NaN
20776,20200116,WA,0.0,NaN,NaN,NaN,totalTestEncountersViral,NaN,NaN,NaN,...,NaN,0,0,650501e005a5ee86d93c5f32dda56735ea2af967,0,0,0,0,0,NaN
20775,20200117,WA,0.0,NaN,NaN,NaN,totalTestEncountersViral,NaN,NaN,NaN,...,NaN,0,0,7cefac6b3681020741ca30f45399a7b22f2e45b4,0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32,20210307,NE,203026.0,NaN,771128.0,NaN,totalTestsViral,2421684.0,137.0,6237.0,...,NaN,0,8,3f55dc5e02818a3abbd58e07cf80bdfe4abc60f1,0,0,0,0,0,NaN
31,20210307,ND,100391.0,5463.0,305912.0,NaN,totalTestEncountersViral,1425146.0,23.0,3880.0,...,NaN,0,2,ee1d9ce00226b7456452f7d4f6674248577e0c4b,0,0,0,0,0,NaN
30,20210307,NC,872176.0,112559.0,NaN,NaN,totalTestsViral,9688838.0,1179.0,NaN,...,NaN,0,0,d9ca67dd72ba6f8a8506ebb734fd25b0b8067608,0,0,0,0,0,NaN
28,20210307,MS,297581.0,113303.0,1459374.0,NaN,posNeg,1756955.0,419.0,9162.0,...,NaN,3,0,38d600ef762a2cde624501169ffae710e94913fe,0,0,0,0,0,NaN
0,20210307,AK,56886.0,NaN,NaN,NaN,totalTestsViral,1731628.0,33.0,1293.0,...,NaN,0,0,dc4bccd4bb885349d7e94d6fed058e285d4be164,0,0,0,0,0,NaN

In [6]:
# Cambiamos formatos
df['date'] = pd.to_datetime(df['date'], format='%Y%m%d')
df['date'] # Si seleccionamos una sola columna devuelve una serie en lugar de un DataFrame

df['state'] = df['state'].astype('string')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20780 entries, 0 to 20779
Data columns (total 56 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   date                         20780 non-null  datetime64[ns]
 1   state                        20780 non-null  string
 2   positive                     20592 non-null  float64
 3   probableCases                9271 non-null   float64
 4   negative                     13290 non-null  float64
 5   pending                      2138 non-null   float64
 6   totalTestResultsSource       20780 non-null  object
 7   totalTestResults             20614 non-null  float64
 8   hospitalizedCurrently        17339 non-null  float64
 9   hospitalizedCumulative       12382 non-null  float64
 10  inIcuCurrently               11636 non-null  float64
 11  inIcuCumulative              3789 non-null   float64
 12  onVentilatorCurrently        9126 non-null   float64
 13  onVentilatorCumulative       1290 non-null   float64
 14  recovered                    12003 non-null  float64
 15  lastUpdateEt                 20164 non-null  object
 16  dateModified                 20164 non-null  object
 17  checkTimeEt                  20164 non-null  object
 18  death                        19930 non-null  float64
 19  hospitalized                 12382 non-null  float64
 20  hospitalizedDischarged       3070 non-null   float64
 21  dateChecked                  20164 non-null  object
 22  totalTestsViral              14516 non-null  float64
 23  positiveTestsViral           8958 non-null   float64
 24  negativeTestsViral           5024 non-null   float64
 25  positiveCasesViral           14246 non-null  float64
 26  deathConfirmed               9422 non-null   float64
 27  deathProbable                7593 non-null   float64
 28  totalTestEncountersViral     5231 non-null   float64
 29  totalTestsPeopleViral        9197 non-null   float64
 30  totalTestsAntibody           4789 non-null   float64
 31  positiveTestsAntibody        3346 non-null   float64
 32  negativeTestsAntibody        1458 non-null   float64
 33  totalTestsPeopleAntibody     2200 non-null   float64
 34  positiveTestsPeopleAntibody  1094 non-null   float64
 35  negativeTestsPeopleAntibody  972 non-null    float64
 36  totalTestsPeopleAntigen      999 non-null    float64
 37  positiveTestsPeopleAntigen   633 non-null    float64
 38  totalTestsAntigen            3421 non-null   float64
 39  positiveTestsAntigen         2233 non-null   float64
 40  fips                         20780 non-null  int64
 41  positiveIncrease             20780 non-null  int64
 42  negativeIncrease             20780 non-null  int64
 43  total                        20780 non-null  int64
 44  totalTestResultsIncrease     20780 non-null  int64
 45  posNeg                       20780 non-null  int64
 46  dataQualityGrade             0 non-null      float64
 47  deathIncrease                20780 non-null  int64
 48  hospitalizedIncrease         20780 non-null  int64
 49  hash                         20780 non-null  object
 50  commercialScore              20780 non-null  int64
 51  negativeRegularScore         20780 non-null  int64
 52  negativeScore                20780 non-null  int64
 53  positiveScore                20780 non-null  int64
 54  score                        20780 non-null  int64
 55  grade                        0 non-null      float64
dtypes: datetime64[ns](1), float64(35), int64(13), object(6), string(1)
memory usage: 8.9+ MB

In [7]:

# Aplicamos un filtro
df['state']

state_AK = df['state']=='AK' # Trae todos los registros en que el estado sea AK
state_AK
df[state_AK]

,date,state,positive,probableCases,negative,pending,totalTestResultsSource,totalTestResults,hospitalizedCurrently,hospitalizedCumulative,...,dataQualityGrade,deathIncrease,hospitalizedIncrease,hash,commercialScore,negativeRegularScore,negativeScore,positiveScore,score,grade
0,2021-03-07,AK,56886.0,NaN,NaN,NaN,totalTestsViral,1731628.0,33.0,1293.0,...,NaN,0,0,dc4bccd4bb885349d7e94d6fed058e285d4be164,0,0,0,0,0,NaN
56,2021-03-06,AK,56886.0,NaN,NaN,NaN,totalTestsViral,1731628.0,33.0,1293.0,...,NaN,0,0,749716d5cc5eb3b785af328a6c27e951ea62ffc2,0,0,0,0,0,NaN
112,2021-03-05,AK,56886.0,NaN,NaN,NaN,totalTestsViral,1731628.0,33.0,1293.0,...,NaN,2,3,7c69ab3363700e0bfc193bc3374d28a89a0d1102,0,0,0,0,0,NaN
168,2021-03-04,AK,56745.0,NaN,NaN,NaN,totalTestsViral,1724484.0,32.0,1290.0,...,NaN,0,5,bc7a5cc276540e2ec8f649ab256aa42f63777463,0,0,0,0,0,NaN
224,2021-03-03,AK,56605.0,NaN,NaN,NaN,totalTestsViral,1711018.0,26.0,1285.0,...,NaN,1,-1,06e88c66f6d974e25a99aebd3d4be26ac862a54b,0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20247,2020-03-10,AK,NaN,NaN,NaN,9.0,totalTestsViral,23.0,NaN,1.0,...,NaN,0,0,41ecc8af507387301652e0bb695c90af3caca45d,0,0,0,0,0,NaN
20298,2020-03-09,AK,NaN,NaN,NaN,9.0,totalTestsViral,23.0,NaN,1.0,...,NaN,0,1,e5fdecc645ef8aa383bb58cae9bdaf905ab33583,0,0,0,0,0,NaN
20349,2020-03-08,AK,NaN,NaN,NaN,6.0,totalTestsViral,14.0,NaN,NaN,...,NaN,0,0,c90ce1a21475c44727e5853c22c009321728270c,0,0,0,0,0,NaN
20400,2020-03-07,AK,NaN,NaN,NaN,2.0,totalTestsViral,12.0,NaN,NaN,...,NaN,0,0,7162c5ea37dd3e1693bfb3c2b9e97fe5e518755d,0,0,0,0,0,NaN
20451,2020-03-06,AK,NaN,NaN,NaN,1.0,totalTestsViral,8.0,NaN,NaN,...,NaN,0,0,a342f77e8bb779edc91c9e1a1be309cd4338356b,0,0,0,0,0,NaN

In [8]:
# Agregamos un campo o columna nueva
df['letalidad'] = df['death'] / df['positive']
df.columns

Index(['date', 'state', 'positive', 'probableCases', 'negative', 'pending',
       'totalTestResultsSource', 'totalTestResults', 'hospitalizedCurrently',
       'hospitalizedCumulative', 'inIcuCurrently', 'inIcuCumulative',
       'onVentilatorCurrently', 'onVentilatorCumulative', 'recovered',
       'lastUpdateEt', 'dateModified', 'checkTimeEt', 'death', 'hospitalized',
       'hospitalizedDischarged', 'dateChecked', 'totalTestsViral',
       'positiveTestsViral', 'negativeTestsViral', 'positiveCasesViral',
       'deathConfirmed', 'deathProbable', 'totalTestEncountersViral',
       'totalTestsPeopleViral', 'totalTestsAntibody', 'positiveTestsAntibody',
       'negativeTestsAntibody', 'totalTestsPeopleAntibody',
       'positiveTestsPeopleAntibody', 'negativeTestsPeopleAntibody',
       'totalTestsPeopleAntigen', 'positiveTestsPeopleAntigen',
       'totalTestsAntigen', 'positiveTestsAntigen', 'fips', 'positiveIncrease',
       'negativeIncrease', 'total', 'totalTestResultsIncrease', 'posNeg',
       'dataQualityGrade', 'deathIncrease', 'hospitalizedIncrease', 'hash',
       'commercialScore', 'negativeRegularScore', 'negativeScore',
       'positiveScore', 'score', 'grade', 'letalidad'],
      dtype='object')

In [9]:
# Podemos generar una tabla pivot
pd.pivot_table(df, values='letalidad', index=['date'],
                    columns=['state'], aggfunc='mean')

state,AK,AL,AR,AZ,CA,CO,CT,DC,DE,FL,...,TN,TX,UT,VA,VI,VT,WA,WI,WV,WY
date,,,,,,,,,,,,,,,,,,,,,
2020-02-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.166667,NaN,NaN,NaN
2020-02-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.153846,NaN,NaN,NaN
2020-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.266667,NaN,NaN,NaN
2020-02-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.277778,NaN,NaN,NaN
2020-03-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.307692,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-03-03,0.005353,0.020173,0.016270,0.019622,0.015144,0.013830,0.027071,0.025062,0.016471,0.016852,...,0.014730,0.016356,0.005245,0.016076,0.009276,0.013366,0.014609,0.011418,0.017437,0.012487
2021-03-04,0.005340,0.020266,0.016287,0.019711,0.015207,0.013796,0.027040,0.024967,0.016476,0.016865,...,0.014755,0.016425,0.005245,0.016094,0.009246,0.013196,0.014645,0.011424,0.017403,0.012471
2021-03-05,0.005362,0.020289,0.016289,0.019759,0.015301,0.013772,0.027000,0.024974,0.016535,0.016886,...,0.014770,0.016478,0.005269,0.016170,0.009211,0.013086,0.014667,0.011430,0.017433,0.012453
2021-03-06,0.005362,0.020322,0.016316,0.019783,0.015401,0.013737,0.027000,0.024956,0.016610,0.016901,...,0.014757,0.016531,0.005275,0.016285,0.009211,0.013029,0.014660,0.011431,0.017428,0.012453
2021-03-07,0.005362,0.020303,0.016375,0.019757,0.015458,0.013717,0.027000,0.024868,0.016672,0.016900,...,0.014757,0.016544,0.005271,0.016384,0.009211,0.012933,0.014631,0.011431,0.017423,0.012453

In [10]:
# Guardamos el DF generado
df.to_csv('local/Bajadas/df_covid_por_estado.csv', index=False) # en este caso lo guardamos en nuestra carpeta local

OSError: Cannot save file into a non-existent directory: 'local\Bajadas'